<?php

namespace App\Http\Requests\Admin\Post;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required',
            'slug' => 'required|unique:slugs,slug,'.$this->slugs['id']  ,
            'description' => 'required',
            'image'=>'required',
            'body'=>'required',
            'cate.*' => 'required|exists:categories,id',
            'tag.*' => 'exists:tags,id',
        ];
    }
    public function messages()
    {
        return [
            'title.required'=>'Vui lòng nhập tiêu đề bài viết',
            'slug.required'=>'Vui lòng nhập slug bài viết',
            'slug.unique'=>'Slug đã tồn tại',
            'image.required'=>'Vui lòng nhập ảnh đại diện bài viết',
            'body.required'=>'Vui lòng nhập nội dung bài viết',
            'cate.required'=>'Vui lòng nhập danh mục bài viết'
        ]; // TODO: Change the autogenerated stub
    }
}
